#!/bin/bash

set -eu

if [ $# = 0 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  cat <<EOF
Usage: $0 <service> [command...]

  Bash shell                        $0 <backend|frontend|worker>
  Strapi console                    $0 backend console
  PostgreSQL console                $0 postgres console
  Redis console                     $0 redis console
  Mail console                      $0 mail console

  Run all tests                     $0 test
  Run <service> tests               $0 <backend|frontend|worker> test
  Watch <service> tests             $0 <backend|frontend|worker> watch

  Run npm install in node services  $0 install
  Apply auto-formatting (prettier)  $0 pretty
  Run linter (eslint)               $0 lint
  Add fake data                     $0 fake
  (Re)build Strapi admin            $0 build-admin
  Reset database                    $0 reset-db
  Clean containers, cache, etc...   $0 clean
EOF
  exit 1
fi

SERVICE="$1"
shift

case "$SERVICE" in
  frontend)
    if [ "$*" == "test" ]; then
      set npm run test
    elif [ "$*" == "watch" ]; then
      set npm run watch
    fi
    ;;
  backend|strapi)
    SERVICE="backend"
    if [ "$*" == "test" ]; then
      set npm run test
    elif [ "$*" == "watch" ]; then
      set npm run watch
    elif [ "$*" == "build-admin" ]; then
      set bash -c 'rm -rf build/* cache/* && npx strapi build'
    elif [ "$*" == "console" ]; then
      set npx -c 'PORT=1338 strapi console'
    elif [ "$*" == "fake" ]; then
      set bash -c 'node lib/fake'
    fi
    ;;
  mail)
    SERVICE="mail"
    if [ "$*" == "console" ]; then
      set mail
    fi
    ;;
  db|postgres)
    SERVICE="postgres"
    if [ "$*" == "console" ]; then
      set psql -U strapi
    fi
    ;;
  redis)
    if [ "$*" == "console" ]; then
      set redis-cli
    fi
    ;;
  worker)
    if [ "$*" == "test" ]; then
      set npm run test
    elif [ "$*" == "watch" ]; then
      set npm run watch
    fi
    ;;
  test)
    "$0" backend test
    "$0" frontend test
    "$0" worker test
    exit 0
    ;;
  install)
    "$0" backend npm install
    "$0" frontend npm install
    "$0" worker npm install
    exit 0
    ;;
  pretty|prettier)
    test -d node_modules || npm install --silent
    npm run prettier
    exit 0
    ;;
  lint|eslint)
    test -d node_modules || npm install --silent
    npm run eslint
    exit 0
    ;;
  fake)
    "$0" backend fake
    exit 0
    ;;
  build-admin)
    "$0" backend build-admin
    exit 0
    ;;
  reset-db|reload-db)
    cd "$(dirname "$0")"
    docker-compose stop -t 1 backend postgres
    docker-compose rm -f postgres
    docker volume prune -f
    rm -rf backend/public/uploads/*
    docker-compose up -d backend postgres
    exit 0
    ;;
  clean)
    cd "$(dirname "$0")"
    docker-compose down
    if docker image ls | grep -q pujaslive; then
      docker image rm $(docker image ls | grep pujaslive | tr -s ' ' | cut -d ' ' -f 3)
    fi
    docker image prune -f
    if docker volume ls -q | grep -q pujaslive; then
      docker volume rm $(docker volume ls -q | grep pujaslive)
    fi
    docker volume prune -f
    rm -rf backend/.cache backend/.tmp backend/build \
          backend/exports backend/node_modules \
          backend/public/uploads/* \
          frontend/.next frontend/node_modules \
          logs/deploy logs/worker \
          worker/build worker/node_modules
    exit 0
    ;;
  *)
    echo "No such service: $SERVICE"
    exit 1
    ;;
esac

if [ $# = 0 ]; then
  set bash
fi

COMMAND=run
SERVICE_ID=$(docker-compose ps -q $SERVICE)
if echo "$SERVICE_ID" | grep -q .; then
  if docker ps -qa --filter status=running \
                   --filter "id=$SERVICE_ID" | grep -q .; then
    COMMAND=exec
  fi
fi

case "$SERVICE" in
  backend|frontend|worker)
    set -- /app/docker/run "$SERVICE" "$@"
    ;;
esac

echo "> docker-compose $COMMAND $SERVICE $@"
docker-compose "$COMMAND" "$SERVICE" "$@"

if test "$COMMAND" = "run"; then
  docker-compose rm -vf > /dev/null 2>&1
fi
