#!/bin/bash

set -eu

if [ $# = 0 ]; then
  echo "Usage: $0 <service>"
  exit 1
fi

SERVICE="$1"

cd "/app/$SERVICE"

if [ $(ls node_modules | wc -l) = 0 ] || \
   [ $(ls ../shared/node_modules | wc -l) = 0 ]; then
  echo "Installing node modules..."
  npm install --silent
fi

if [ "$SERVICE" = backend ] && [ $(ls build | wc -l) = 0 ]; then
  npm run build
fi

npm run dev
