#!/bin/bash

set -eu

if [ $# = 0 ]; then
  echo "Usage: $0 <service> command [args...]"
  exit 1
fi

SERVICE="$1"
shift

case "$SERVICE" in
  backend)
    VOLUME_DIRS=".cache build"
    ;;
  frontend)
    VOLUME_DIRS=".next"
    ;;
  worker)
    VOLUME_DIRS=""
    ;;
  *)
    echo "Invalid service: $SERVICE"
    exit 1
esac

cd "/app/$SERVICE"

uid=$(stat -c %u .)
gid=$(stat -c %g .)

if [ $uid = 0 ]; then
  # Host is Mac/Windows, run as root...
  user=root
else
  user=node
  groupmod -g $gid $user
  usermod -u $uid -g $gid $user 2> /dev/null
  chown -R node:node /home/node
  chown node:node node_modules $VOLUME_DIRS
fi

if test "$*" = bash; then
  exec su -s /bin/bash $user
else
  cmd="$(printf '"%q" ' "$@")"
  exec su -c "$cmd" $user
fi
