#!/bin/bash

set -eu

if [ $# = 0 ]; then
  echo "Usage: $0 <service> command [args...]"
  exit 1
fi

SERVICE="$1"
shift

DIR="/app/$SERVICE"
VOLUME_DIRS=

case "$SERVICE" in
  backend)
    VOLUME_DIRS="/app/backend/.cache /app/backend/build"
    ;;
  frontend)
    VOLUME_DIRS="/app/frontend/.next"
    ;;
  shared)
    SERVICE=worker
    DIR=/app/shared
    ;;
  worker)
    ;;
  *)
    echo "Invalid service: $SERVICE"
    exit 1
esac

uid=$(stat -c %u .)
gid=$(stat -c %g .)

if [ $uid = 0 ]; then
  # Host is Mac/Windows, run as root...
  user=root
else
  user=node
  groupmod -g $gid $user
  usermod -u $uid -g $gid $user 2> /dev/null
  chown -R node:node /home/node
  chown node:node \
    /app/$SERVICE/node_modules \
    /app/shared/node_modules \
    $VOLUME_DIRS
fi

cd "$DIR"

if test "$*" = bash; then
  exec su -s /bin/bash $user
else
  cmd="$(for i in "$@"; do echo -n "${i@Q} "; done)"
  exec su -c "$cmd" $user
fi
